export const HOME_PRODUCTS_LIST = "HOME_PRODUCTS_LIST";
export const OPEN_CART = "OPEN_CART";
export const AFTER_REMOVE_CART = "AFTER_REMOVE_CART";
export const IS_ORDER_CREATED = "IS_ORDER_CREATED";
export const IS_ORDER_HIT = "IS_ORDER_HIT";
